### ISSUE TITLE
Doesn't build on linux because ncursesw could not be found.

### ISSUE THREAD

**Issue by CamilleScholtz** [uhlin/swirc#1]
I do heave the headers installed, and compiled my ncurses with wchar support. merging the LINUX #if with OSX and BSD fixes the problem.

**Comment by uhlin** [comment]
Not sure how to fix this in a good way. Because on the distro I use it expects the include path to be ncursesw/curses.h and ncursesw/panel.h

**Comment by CamilleScholtz** [comment]
What distro do you use? Anyways, I think ncmpcp does something with ncrusesw-config: https://github.com/arybczak/ncmpcpp/blob/4130d3ba241f51199d5cefacd6e453f10bcb97d0/configure.ac#L246

**Comment by uhlin** [comment]
I am on Debian. I'm gonna figure out a solution. What's your distro?

**Comment by CamilleScholtz** [comment]
CRUX

**Comment by uhlin** [comment]
This fixes the issue, right?
