### ISSUE TITLE
Resizing the window leads to a fatal error/crash on Windows 10

### ISSUE THREAD

**Issue by zdm505** [uhlin/swirc#10]
Swirc Version: 3.3.1
OS: Windows 10 Home, Version 21H1, Build 19043.1237

Resizing the window leads to a fatal error and crashes the program: 
`term_resize_panel: newwin(1, 120, 0, 0): unable to create new window`

![image](https://user-images.githubusercontent.com/77480027/134762064-acba150d-dbf4-4545-b58a-67ded2a339c1.png)

 A lot of rendering artifacts occur during the resizing, and the window always reverts itself back to the default size. Is this intended behavior?

See also video: https://streamable.com/avlnbi

**Comment by uhlin** [comment]
Thanks for your report! It isn't the behavior I want but I have been aware of it. I will look into this.

**Comment by uhlin** [comment]
I will close this issue in the next commit with a small fix that at least allows the window to be resized once, doing it the [PDCurses](https://pdcurses.org/) way...
3.3.2 is close now.
