### ISSUE TITLE
Window support like irssi?

### ISSUE THREAD

**Issue by diizzyy** [uhlin/swirc#2]
Hi,

Looks like a promising project but it seems to lack some kind of window feature irssi or am I missing something?

Best regards,
Daniel

**Comment by uhlin** [comment]
Thanks. Not sure what you mean with window feature. It's possible to change windows with ctrl+p (previous) and ctrl+n (next). But it's not possible to split windows or something else (yet).

**Comment by diizzyy** [comment]
Ahh, split windows and such... Sorry for the confusion.

**Comment by uhlin** [comment]
Closing.
