### ISSUE TITLE
Issues with protocol colon escaping.

### ISSUE THREAD

**Issue by MakeItGreatAgain** [uhlin/swirc#6]
IRC protocol colon escaping seems to be done haphazardly. For example:

When a channel key containing a ":" is set, the ":" is erroneously stripped from display.

Server sending a "MODE #test +kl a:b :99" parses as: "mode/[#test] [+kl ab 99] by user". The ':' should not be stripped as part of a channel key, but it it is.

(Servers may allow a colon in the key as long as the colon is not the first character).

However, it is displayed on the status bar as [#test(+klnt a:b :99)]" which is also incorrect, as the ':' before 99 (last argument) should have been stripped here but is not.

When colon escaping is used in non-traditional places it seems to not always be escaped - for example, on inspircd (testnet.inspircd.org) channel modes are often misparsed, for example: "[#test(:+nt)]".

The practice of colon-escaping all final arguments, including those without spaces, is unusual but not in violation of the IRC RFC.

**Comment by MakeItGreatAgain** [comment]
Another colon escaping issue noticed - timestamps that are validly (but not required by protocol to be) colon escaped aren't stripped before the values are used, which leads to some numerics failing to parse, for example:

[23:52] [-] [*] event_topic_creator: error: expected numeric string
[00:19] [-] [*] event_channelCreatedWhen: error: expected numeric string

**Comment by MakeItGreatAgain** [comment]
A few servers that were implemented from the RFC (but not derived from historical code) can be used to reproduce the behavior - for example, inspircd is pedantically RFC-complaint but not derived from existing code - it always colon escapes the final arguments, and thus can be used for testing - their test server is testnet.inspircd.org

**Comment by uhlin** [comment]
Thank you for your reports. Working on them in a series of commits. And don't be afraid of reporting again if I got something wrong or you find some other bug.
