### ISSUE TITLE
Reproducible crash from protocol fuzzing 

### ISSUE THREAD

**Issue by MakeItGreatAgain** [uhlin/swirc#8]
Protocol fuzzing found the following reproducible crash:

> (start netcat server with attached fuzzing data.)

`nc -l 6667 <`[`fuzz.log`](https://github.com/uhlin/swirc/files/3300022/fuzz.log)`&`

> (start swirc)

`gdb swirc`
`(gdb) run -c localhost -n x -u x -r x`
`Starting program: swirc -c brrpi02 -n x -u x -r x`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".`
`FATAL: In events/names.c: Can't find a window with label pp 
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`

> (crash backtrace)

`Thread 3 "swirc" received signal SIGABRT, Aborted.`
`[Switching to Thread 0x752ff440 (LWP 12067)]`
`__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51`
`51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.`
`(gdb) bt`
`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51`
`#1  0x76925824 in __GI_abort () at abort.c:89`
`#2  0x00021d7c in hInstall (ctx=0x752fec14) at src/events/names.c:221`
`#3  0x00021e1c in event_names_htbl_insert (nick=0x74900f09 "c", channel=0x74901610 "pp  ", 'N' <repeats 99 times>) at src/events/names.c:242`
`#4  0x0001c2cc in event_join (compo=0x74900c88) at src/events/channel.cpp:129`
`#5  0x0002f1a4 in irc_search_and_route_event (compo=0x74900c88) at src/irc.c:499`
`#6  0x0002f4e8 in ProcessProtoMsg (token=0x74900948 ":c JOIN pp  ", 'N' <repeats 99 times>) at src/irc.c:552`
`#7  0x0002f7ec in irc_handle_interpret_events (recvbuffer=0x74900470 ":127.0.0.1 001 joseph :a", message_concat=0x752fedb8, state=0x752fedbc) at src/irc.c:646`
`#8  0x0003403c in net_irc_listen (connection_lost=0x752fee3b) at src/network.cpp:382`
`#9  0x00032230 in listenThread_fn (arg=0x0) at src/net-unix.c:150`
`#10 0x76c92fc4 in start_thread (arg=0x752ff440) at pthread_create.c:458`
`#11 0x769ca038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6`
`Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

**Comment by uhlin** [comment]
Thank you very much for this (and the other reports). I'm working on a solution.
