### ISSUE TITLE
E-Mail

### ISSUE THREAD

**Issue by michaelortmann** [uhlin/swirc#9]
Hi,

ive found a bug in swirc, that i would prefer to report via e-mail instead of public github.

An email to bredband.net bounced back.

How can i proceed?

Kind regards,
Michael

**Comment by uhlin** [comment]
Hi Michael!
Thanks for reporting.
Ok, markus.uhlin@bredband.net should work, did you try twice?
If it doesn't try markus@dataswamp.org
Kind regards
Markus

**Comment by michaelortmann** [comment]
my second mail got thru, thank you!
